### ISSUE TITLE
PIMixin: Fix set_timeseries with units - [merged]

### ISSUE THREAD

**Issue by SGeeversAtVortech** [Deltares/rtc-tools#1438]
In GitLab by @vreeken on Oct 5, 2019, 11:53

_Merges fix-pi-units -> master_

Regression in 623fc2cf (IO refactor).

PI files also support units, and therefore set_timeseries when using
PIMixin used to have (before the commit mentioned above) a unit
argument. The base functionality of IOMixin does not implement this, so
we override it to fix the regression.

**Comment by SGeeversAtVortech** [comment]
In GitLab by @vreeken on Oct 7, 2019, 13:07

added 2 commits

<ul><li>b772414d - 1 commit from branch <code>master</code></li><li>14615ad0 - PIMixin: Fix set_timeseries with units</li></ul>

[Compare with previous version](/deltares/rtc-tools/merge_requests/337/diffs?diff_id=57678403&start_sha=5deb94ad1e4921d5f24f23e3d4331cd0c3ee8a8b)

**Comment by SGeeversAtVortech** [comment]
In GitLab by @vreeken on Oct 7, 2019, 13:07

enabled an automatic merge when the pipeline for 14615ad0547669613aeb5b6b2fc87fa8feacc1c4 succeeds

**Comment by SGeeversAtVortech** [comment]
In GitLab by @vreeken on Oct 7, 2019, 13:17

merged
